# Configuração Web (Blazor) separada para Coolify
# Este arquivo configura apenas a aplicação web Blazor

# VARIÁVEIS DE AMBIENTE OBRIGATÓRIAS (Configure no Coolify):
# DB_PASSWORD=sua_senha_postgres_segura
# JWT_AUDIENCE=https://seu-dominio.com  
# JWT_SIGNING_KEY=sua_chave_jwt_secreta_aqui
# WEB_DOMAIN=seu-dominio.com
# API_URL=http://nome_do_container_api:5004 (ou URL externa da API)
# DB_HOST=nome_do_container_postgres (ou IP se externo)

version: '3.8'

services:
  # Aplicação Web Blazor
  web:
    build:
      context: ./abastecaonline
      dockerfile: Dockerfile
    container_name: abastecimento-web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5003
      - ASPNETCORE_HTTP_PORTS=5003
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ASPNETCORE_SHUTDOWNTIMEOUTSECONDS=30
      
      # Database Connection
      - ConnectionStrings__ConnectionString=XpoProvider=Postgres;User ID=postgres;Password=${DB_PASSWORD};Server=${DB_HOST:-postgres};Port=5432;Database=abastecimento;Pooling=true;MinPoolSize=5;MaxPoolSize=20;CommandTimeout=30;
      
      # JWT Configuration
      - Authentication__Jwt__Audience=${JWT_AUDIENCE}
      - Authentication__Jwt__IssuerSigningKey=${JWT_SIGNING_KEY}
      - Authentication__Jwt__Issuer=XafSecurity
      
      # API Configuration
      - ApiUrl=${API_URL:-http://api:5004}
      - ApiBaseUrl=${API_URL:-http://api:5004}
      
      # Database Environment Variables
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=5432
      - DB_NAME=abastecimento
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      
      # Application Settings
      - AllowedHosts=*
      - DataProtection__ApplicationName=AbastecimentoWeb
      
      # Logging Configuration
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft=Warning
      - Logging__LogLevel__DevExpress.ExpressApp=Information
      
      # Blazor Specific Settings
      - CircuitOptions__DetailedErrors=false
      - CircuitOptions__DisconnectedCircuitMaxRetained=100
      - CircuitOptions__DisconnectedCircuitRetentionPeriod=00:03:00
      - CircuitOptions__JSInteropDefaultCallTimeout=00:01:00
      - CircuitOptions__MaxBufferedUnacknowledgedRenderBatches=10
      
    volumes:
      - web_keys:/app/keys
      - web_logs:/app/logs
    ports:
      - "5003:5003"
    healthcheck:
      test: |
        curl -f http://localhost:5003/health || 
        curl -f http://localhost:5003/ || 
        wget --no-verbose --tries=1 --spider http://localhost:5003/health ||
        exit 1
      interval: 30s
      timeout: 15s
      retries: 8
      start_period: 150s  # Blazor precisa de mais tempo para inicializar
    restart: unless-stopped
    networks:
      - abastecimento
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    labels:
      - "coolify.managed=true"
      - "coolify.name=abastecimento-web"
      - "coolify.domain=${WEB_DOMAIN}"
      - "coolify.port=5003"
      - "coolify.https=true"
      - "coolify.type=application"

volumes:
  web_keys:
    driver: local
    labels:
      - "coolify.managed=true"
  web_logs:
    driver: local
    labels:
      - "coolify.managed=true"

networks:
  abastecimento:
    external: true
    name: abastecimento-network