# Configuração para deploy no Coolify - Versão sem Health Checks HTTP
# Use este arquivo se as aplicações não tiverem endpoints /health implementados

# INSTRUÇÕES DE CONFIGURAÇÃO NO COOLIFY:
# 1. Crie um novo projeto
# 2. Adicione este repositório Git
# 3. Configure as variáveis de ambiente listadas abaixo
# 4. Execute o deploy

# VARIÁVEIS DE AMBIENTE OBRIGATÓRIAS (Configure no Coolify):
# DB_PASSWORD=sua_senha_postgres_segura
# JWT_AUDIENCE=https://seu-dominio.com  
# JWT_SIGNING_KEY=sua_chave_jwt_secreta_aqui
# API_DOMAIN=api.seu-dominio.com
# WEB_DOMAIN=seu-dominio.com

version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: abastecimento-db
    environment:
      POSTGRES_DB: abastecimento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d abastecimento || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks:
      - abastecimento

  # API Backend
  api:
    build:
      context: ./abastecimento_api
      dockerfile: Dockerfile
    container_name: abastecimento-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5004
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ConnectionStrings__ConnectionString=XpoProvider=Postgres;User ID=postgres;Password=${DB_PASSWORD};Server=postgres;Port=5432;Database=abastecimento
      - Authentication__Jwt__Audience=${JWT_AUDIENCE}
      - Authentication__Jwt__IssuerSigningKey=${JWT_SIGNING_KEY}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=abastecimento
      - DB_PASSWORD=${DB_PASSWORD}
      - AllowedHosts=*
    ports:
      - "5004:5004"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep :5004 | grep LISTEN || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - abastecimento

  # Aplicação Web Blazor
  web:
    build:
      context: ./abastecaonline
      dockerfile: Dockerfile
    container_name: abastecimento-web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5003
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ConnectionStrings__ConnectionString=XpoProvider=Postgres;User ID=postgres;Password=${DB_PASSWORD};Server=postgres;Port=5432;Database=abastecimento
      - Authentication__Jwt__Audience=${JWT_AUDIENCE}
      - Authentication__Jwt__IssuerSigningKey=${JWT_SIGNING_KEY}
      - ApiUrl=http://api:5004
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=abastecimento
      - DB_PASSWORD=${DB_PASSWORD}
      - AllowedHosts=*
    ports:
      - "5003:5003"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep :5003 | grep LISTEN || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    restart: unless-stopped
    networks:
      - abastecimento
    labels:
      # Labels para proxy reverso do Coolify
      - "coolify.managed=true"
      - "coolify.name=abastecimento-web"
      - "coolify.domain=${WEB_DOMAIN}"
      - "coolify.port=5003"
      - "coolify.https=true"

volumes:
  postgres_data:
    driver: local

networks:
  abastecimento:
    driver: bridge